### ISSUE TITLE
Nothing is committed to repo yet. 

### ISSUE THREAD

**Issue by ZainKergaye** [cshmookler/status_bar#1]
Where are all the important files? 

I can't make a PR but let me help with your readme: 

# Status bar config for DWM
These are the config files for my instance of DWM, Screenshot is below. 

## To Install
    git clone https://github.com/cshmookler/status_bar
    mv status_bar /home/$USER/.config/

**Comment by ZainKergaye** [comment]
Don't forget to let me make it a PR so I get more points on my GH profile

**Comment by cshmookler** [comment]
Files have been uploaded.  As of now (2024-01-28) the program is incomplete. Should be complete by February.
